defaults:
  - scope:
      path: "pages/*"
      type: "pages"
    values:
      permalink: /:basename/
      baseurl: "../"

  - scope:
      path: "redirects/*"
      type: "pages"
    values:
      permalink: /:basename/
      baseurl: "../"

  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      og-title: Centro Cultural Esplanada - CCE
      og-description: "Centro do Opus Dei para homens em São José dos Campos, São Paulo, Brasil."
      og-url: /
      og-image-path: /assets/images/a_ogp/
      og-image: ogp-default.png
